name: 'nyc_taxi'
version: '1.0.0'
config-version: 2

profile: 'nyc_taxi'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  nyc_taxi:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  nyc_taxi:
    +quote_columns: false