version: 2

models:
  - name: stg_yellow_trips
    columns:
      - name: pickup_datetime
        tests:
          - not_null
      - name: dropoff_datetime
        tests:
          - not_null
      - name: pickup_location_id
        tests:
          - not_null
      - name: dropoff_location_id
        tests:
          - not_null

  - name: stg_taxi_zones
    columns:
      - name: location_id
        tests:
          - not_null
          - unique